version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - dem

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/postgres_python
    depends_on:
      - postgres
    networks:
      - dem

networks:
  dem: